### ISSUE TITLE
Makefile problems

### ISSUE THREAD

**Issue by kvkarandashev** [qmlcode/qmllib#5]
Running `make` command yields error message:

```
mamba env create -f ./environment_dev.yaml -p ./env --quiet
usage: mamba [-h] [--version] [--slow SLOW] [--enable-coverage] [--coverage-file COVERAGE_FILE] [--format FORMAT] [--no-color]
             [--tags TAGS]
             [specs ...]
mamba: error: unrecognized arguments: -p ./env --quiet
make: *** [Makefile:13: env] Error 
```

I am running this in a fresh environment with python 3.12.2 and the following packages installed:

Package    Version
---------- -------
args       0.1.0
clint      0.5.1
coverage   7.4.4
mamba      0.11.3
pip        24.0
setuptools 69.2.0
wheel      0.43.0

Possibly relevant, I decided to see what happens when I uncomment "-p ./env --quiet", yielding the following error:
```
mamba env create -f ./environment_dev.yaml #-p ./env --quiet
Traceback (most recent call last):
  File "/home/konstantin/miniconda3/envs/testenv/bin/mamba", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/konstantin/miniconda3/envs/testenv/lib/python3.12/site-packages/mamba/cli.py", line 16, in main
    runner = factory.runner()
             ^^^^^^^^^^^^^^^^
  File "/home/konstantin/miniconda3/envs/testenv/lib/python3.12/site-packages/mamba/application_factory.py", line 46, in runner
    self._reporter(),
    ^^^^^^^^^^^^^^^^
  File "/home/konstantin/miniconda3/envs/testenv/lib/python3.12/site-packages/mamba/application_factory.py", line 63, in _reporter
    return reporter.Reporter(self._formatter())
                             ^^^^^^^^^^^^^^^^^
  File "/home/konstantin/miniconda3/envs/testenv/lib/python3.12/site-packages/mamba/application_factory.py", line 73, in _formatter
    return self._custom_formatter()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/konstantin/miniconda3/envs/testenv/lib/python3.12/site-packages/mamba/application_factory.py", line 77, in _custom_formatter
    module = import_module('.'.join(splitted[0:-1]), splitted[-1])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/konstantin/miniconda3/envs/testenv/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'yaml'
make: *** [Makefile:13: env] Error 1
```

**Comment by charnley** [comment]
Weird. I would assume that `mamba` is installed with `yaml` by default. 
Do `pip install pyyaml` in your base Python environment. Or maybe use `conda` to create your python environment.

**Comment by charnley** [comment]
I don't recognise the `mamba` arguments; how did you set up your base environment?

**Comment by andersx** [comment]
Mamba worked for me

```
(base) andersx@beast:~/dev/testmamba$ mamba env create -f environment_dev.yaml
Channels:
 - conda-forge
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: done

Downloading and Extracting Packages:
                                                                                            
Preparing transaction: done                                                                 
Verifying transaction: done                                                                 
Executing transaction: done                                                                 
#                                                                                           
# To activate this environment, use                                                         
#                                                                                           
#     $ conda activate qmllib_dev                                                           
#                                                                                           
# To deactivate an active environment, use                                                  
#                                                                                           
#     $ conda deactivate                                                                    
                                                                                            
(base) andersx@beast:~/dev/testmamba$
``

**Comment by kvkarandashev** [comment]
The mamba arguments displayed in the original post are the ones that Makefile uses.

Despite installing PyYAML 6.0.1 I still get the error:

```
(testenv) konstantin@h:~/qmlcode/qmllib$ mamba env create -f environment_dev.yaml
Traceback (most recent call last):
  File "/home/konstantin/miniconda3/envs/testenv/bin/mamba", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/konstantin/miniconda3/envs/testenv/lib/python3.12/site-packages/mamba/cli.py", line 16, in main
    runner = factory.runner()
             ^^^^^^^^^^^^^^^^
  File "/home/konstantin/miniconda3/envs/testenv/lib/python3.12/site-packages/mamba/application_factory.py", line 46, in runner
    self._reporter(),
    ^^^^^^^^^^^^^^^^
  File "/home/konstantin/miniconda3/envs/testenv/lib/python3.12/site-packages/mamba/application_factory.py", line 63, in _reporter
    return reporter.Reporter(self._formatter())
                             ^^^^^^^^^^^^^^^^^
  File "/home/konstantin/miniconda3/envs/testenv/lib/python3.12/site-packages/mamba/application_factory.py", line 73, in _formatter
    return self._custom_formatter()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/konstantin/miniconda3/envs/testenv/lib/python3.12/site-packages/mamba/application_factory.py", line 77, in _custom_formatter
    module = import_module('.'.join(splitted[0:-1]), splitted[-1])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/konstantin/miniconda3/envs/testenv/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'environment_dev' 
```

Editing this in the beginning of Makefile made it run for me for now:
```
python=python
mamba=conda
pkg=qmllib
pip=pip
pytest=pytest
...
env:
        ${mamba} env create -f ./environment_dev.yaml #-p ./env --quiet
        ${python} -m pre_commit install
        ${python} -m pip install -e .
```

**Comment by charnley** [comment]
I think the `mamba` you are using is incorrect, as the interface should be equivalent to `conda`.  From mamba documentation:
> At the same time, mamba utilizes the same command line parser, package installation and deinstallation code and transaction verification routines as conda to stay as compatible as possible.

However, I will change the default environment creation to `conda` for better transparency.
